name: PlotArea
main: Crow\PlotArea\Main
version: 5.5.0
api: 3.0.0
author: Crow
load: POSTWORLD
description: verwalten Sie sich plötzlich wie nie zuvor!

commands:
  saveplot:
    description: Plot speichern
    usage: "Usage: /saveplot <plotname>"
    permission: saveplot.per
  plotinfo:
    description: Bietet Informationen zu einem Grundstück
    usage: "Usage: /plotinfo"
    permission: plot.info.per
  plotwand:
    description: andere dein rand
    usage: "Usage: /plotwand"
    permission: rand.plot.per
  plot:
    description: Ploteinstellungen
    usage: "Usage: /plot <arg>"
    permission: pa.plotcmd.per
  flushperms:
    description: "Löscht alle Berechtigungen"

permissions:
  pa.plotinfo:
    description: "Bietet Informationen zum Grundstück"
    default: true
  pa.plotcmd:
    description: "Verwenden Sie den Befehl plot"
    default: true
  pa.staff:
    default: op
    children:
      pa.staff.devinfo:
        default: op
      pa.staff.saveplot:
        description: "Grundstücksläden"
        default: op
      pa.staff.plotwand:
        description: "GS-Rand"
        default: op
      pa.staff.plot.addmember:
        description: "Berechtigung zum Hinzufügen eines Mitglieds."
        default: op
      pa.staff.plot.removemember:
        description: "Erlaubnis, Mitglied zu entfernen."
        default: op
      pa.staff.plot.delete:
        description: "Ein Grundstück löschen"
        default: op
      pa.staff.plot.setowner:
        description: "Besitzer festlegen"
        default: op
      pa.staff.plot.setflag:
        description: Ermöglicht dem Benutzer die Verwendung der /plot setflag command
        default: op
      pa.staff.plot.publicchest:
        default: op
      pa.staff.plot.setmaxmembers:
        default: op
      pa.staff.interactbypass:
        default: op
      pa.staff.plot.creategroup:
        default: op
      pa.staff.plot.joingroup:
        default: op
      pa.staff.plot.deletegroup:
        default: op
      pa.staff.plot.leavegroup:
        default: op
      pa.staff.plot.userinfo:
        default: op

